clientdetails:
    clientId: foo
    clientSecret: ""
    authorizedGrantTypes: refresh_token, password
    scope: oauth
    accessTokenValiditySeconds: 1800
    
logging:
  level:
    org.springframework.security: DEBUG